// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "NavbarLinks": {
        "about": "About Us",
        "game": "Games",
        "partner": "Partners",
        "contact": "Contact Us"
    },
    "Header": {
        "title": "We're Getting Ready",
        "desc": "We will back to something amazing. Getting the latest updates about our games. Please sign up to our newsletter.",
        "input": "Enter your email",
        "days": "Days",
        "hours": "Hours",
        "minutes": "Minutes",
        "second": "Second"
    },
    "AboutSection": {
        "title": "About Us",
        "desc": "Browse our selection of free online games and have a great time without leaving the site! Our Kids Games option also includes game reviews, extensive game cheats and walkthroughs, and much more. We have exclusive free downloads, videos, and articles as well. Etech reviews the most popular kids games from all the most popular video gaming platforms, so you don't need to search around for fun anywhere else on the Internet. Explore a whole new world of gaming on Etech.",
        "subDesc": {
            "user": "Users",
            "game": "Games"
        },
        "benefits": {
            "time": {
                "title": "24 - Hour",
                "desc": "24/7 access ensures operators' businesses runs smoothly all year long."
            },
            "design": {
                "title": "Design",
                "desc": "Combining imaginative universes, play dynamics, and unprecedented gameplay, our games transcend the boundaries of the virtual world by weaving innovative gameplay."
            },
            "team": {
                "title": "Team",
                "desc": "Etech is an award-winning, international studio of designers, artists, animators and producers that create content for the biggest names in film and video games."
            }
        }
    },
    "GameSection": {
        "title": "Our Games",
        "desc": "As a pioneer of mobile app gamification, we take pride in originality and individuality, providing global players with state-of-the-art games that feature splendid storylines, sensational sound effects and magnificent animation that never cease to impress."
    },
    "PartnerSection": {
        "title": "Our Partners"
    },
    "Footer": {
        "address": {
            "title": "Address",
            "detail": "Valletta Buildings, South Street, Valletta - VLT 1103 Malta, US",
            "sub": "20 Phan Dang Luu street, Hai Chau District, Danang city, Vietnam"
        },
        "suscribe": {
            "title": "Subscribe",
            "detail": "Subscribe to our newsletter and be the first to know about our updates",
            "input": "Enter your email"
        },
        "phone": "or"
    }
};
export default messages;